market:
  id: "market"
  name: "Market"
  description: "A bustling marketplace with various stalls selling fresh produce, crafts, and trinkets. The air is filled with the mingling aromas of spices, flowers, and street food."
  available_actions:
    - name: "browse_stalls"
      description: "Look through the market stalls"
      requirements: {}
      consequences: []
  connected_locations:
    - "town_square"
    - "garden"
  location_items:
    - id: "ripe_apple"
      name: "Ripe Apple"
      description: "A juicy, red apple that looks perfectly ripe."
      categories: ["CONSUMABLE"]
      weight: 0.2
      stackable: true
      quantity: 1
      effects:
        - attribute: "health"
          value: 5
          description: "A healthy snack restores some energy."
      is_obvious: true
      use_text: "The apple is crisp and delicious, giving you a small energy boost."
    - id: "colorful_scarf"
      name: "Colorful Scarf"
      description: "A handwoven scarf with vibrant patterns. Seems to have been dropped by a shopper."
      categories: ["WEARABLE"]
      slot: "ACCESSORY"
      weight: 0.3
      style_rating: 7
      is_obvious: true
  location_containers:
    - id: "abandoned_basket"
      name: "Abandoned Shopping Basket"
      description: "A wicker shopping basket left unattended. It contains a few items."
      categories: ["CONTAINER"]
      weight: 1.0
      capacity: 5.0
      is_obvious: true
      contents:
        - id: "fresh_bread"
          name: "Fresh Bread"
          description: "A loaf of freshly baked bread, still warm to the touch."
          categories: ["CONSUMABLE"]
          weight: 0.5
          stackable: true
          quantity: 1
          effects:
            - attribute: "health"
              value: 10
              description: "Delicious bread restores health."
          use_text: "The bread is delicious and filling."