town_square:
  id: "town_square"
  name: "Town Square"
  description: "The heart of the town with a beautiful central fountain. People gather here to socialize and relax. The square is lined with benches and decorative plantings. Recently, a festival was held here."
  available_actions:
    - name: "search_fountain"
      description: "Search around the fountain area"
      requirements:
        perception: 7
      consequences:
        - event_type: "AddClue"
          data:
            id: "locket_clue"
            description: "You found a thread that might have come from the locket's chain."
            related_quest: "missing_locket"
            discovered: true
  connected_locations:
    - "warehouse_entrance"
    - "market"
    - "garden"
  location_items:
    - id: "lost_wallet"
      name: "Lost Wallet"
      description: "A worn leather wallet, probably lost by a visitor to the square."
      categories: ["EVIDENCE"]
      weight: 0.2
      is_obvious: true
      contents:
        - id: "wallet_cash"
          name: "Cash"
          description: "A small amount of cash, about $20."
          categories: ["QUEST_ITEM"]
          weight: 0.1
          value: 20
        - id: "business_card"
          name: "Business Card"
          description: "A business card for 'Harbor Shipping Co.' with a handwritten note on the back."
          categories: ["EVIDENCE"]
          weight: 0.05
    - id: "silver_coin"
      name: "Silver Commemorative Coin"
      description: "A special coin minted for the town's centennial celebration. Someone must have dropped it."
      categories: ["QUEST_ITEM"]
      weight: 0.1
      value: 5
      is_obvious: true
    - id: "locket_chain"
      name: "Broken Silver Chain"
      description: "A delicate silver chain that appears to have snapped. It might have held a pendant or locket."
      categories: ["EVIDENCE", "QUEST_ITEM"]
      weight: 0.05
      is_obvious: false
      perception_difficulty: 10
      hidden_clues:
        - "The clasp is intact, suggesting the chain broke elsewhere."
        - "There are traces of something that might be nail polish on one end."