warehouse_entrance:
  id: "warehouse_entrance"
  name: "Warehouse Entrance"
  description: "A imposing metal door stands before you, its surface marked by years of use. The surrounding concrete walls are covered in faded graffiti. The air smells of rust and distant sea salt."
  available_actions:
    - name: "inspect_door"
      description: "Examine the warehouse door closely"
      requirements:
        perception: 8
      consequences:
        - event_type: "AddClue"
          data:
            id: "scratch_marks"
            description: "Recent scratch marks around the lock suggest forced entry"
            related_quest: "main_investigation"
            discovered: false
  connected_locations:
    - "warehouse_office"
    - "parking_lot"
    - "town_square" # Added connection to town for quest accessibility
  location_items:
    - id: "rusty_key"
      is_obvious: true
    - id: "discarded_glove"
      is_obvious: true
    - id: "hidden_lockpick"
      is_obvious: false
      perception_difficulty: 12
  location_containers:
    - id: "trash_bin"
      is_obvious: true
      contents:
        - id: "crumpled_note"
          quantity: 1
