worker_chen:
  id: "worker_chen"
  name: "Sarah Chen"
  dialogue_entry_point: "chen_intro"
  disposition: 65
  location: "warehouse_entrance"
  gender: "female"
  schedule:
    morning: "warehouse_entrance"
    afternoon: "warehouse_office"
    evening: "warehouse_entrance"