items:
  mysterious_key:
    id: "mysterious_key"
    name: "Tarnished Brass Key"
    description: "An old brass key with no obvious markings. It's unclear what it might open."
    categories: ["QUEST_ITEM"]
    weight: 0.1
    hidden_lore: "This style of key was commonly used for security deposit boxes at First National Bank during the 1980s."
    hidden_clues:
      - "There's a tiny engraving on the shaft that reads 'Box 447'"
      - "The wear pattern suggests it's been used frequently, but not recently"
      - "There are faint traces of a blue substance in the grooves"
    hidden_usage: "The unusual size and pattern suggests it might fit older security boxes or safes rather than standard door locks."
    perception_difficulty: 14
    wisdom_difficulty: 11

  torn_photograph:
    id: "torn_photograph"
    name: "Torn Photograph"
    description: "A photograph torn in half. It shows part of a warehouse and what might be a person's arm."
    categories: ["EVIDENCE", "QUEST_ITEM"]
    weight: 0.05
    hidden_clues:
      - "In the background, barely visible, is a sign with partial text '...RBOR 7'"
      - "The lighting and shadows suggest the photo was taken at dusk"
      - "There's a date stamp on the back from 3 years ago"
    perception_difficulty: 12

  rusty_key:
    id: "rusty_key"
    name: "Rusty Key"
    description: "An old, rusty key. It's unclear what it might open."
    categories: ["QUEST_ITEM"]
    weight: 0.1
    hidden_clues:
      - "The rust pattern suggests it's been exposed to moisture recently"
      - "There are small scratches around the teeth, as if it's been used recently"
    perception_difficulty: 8

  crumpled_note:
    id: "crumpled_note"
    name: "Crumpled Note"
    description: "A note that's been crumpled up and thrown away. It contains partial delivery instructions."
    categories: ["EVIDENCE", "QUEST_ITEM"]
    weight: 0.1
    hidden_clues:
      - "The handwriting matches entries in the security logbook"
      - "There's a partial address that seems to be in the industrial district"
      - "The paper has a faint chemical smell"
    perception_difficulty: 10
