---
# Character Archetypes Configuration

character_archetypes:
  analytical:
    id: "analytical"
    name: "Analytical Detective"
    description: "You solve cases through careful observation and deductive reasoning. Your analytical mind excels at connecting evidence and spotting inconsistencies. You prefer to let the facts speak for themselves rather than relying on social pressure."
    starting_skills:
      logic: 3
      perception: 3
      memory: 2
      empathy: 1
      authority: 1
      suggestion: 0
      composure: 1
      agility: 0
      endurance: 1
    starting_equipment_ids:
      - "notebook"
      - "magnifying_glass"
      - "crime_scene_kit"

  persuasive:
    id: "persuasive"
    name: "Persuasive Detective"
    description: "Your exceptional people skills make you a master at extracting information through conversation. You can read emotions, gain trust, and apply pressure when needed. You rely on witness testimony more than physical evidence."
    starting_skills:
      logic: 1
      perception: 1
      memory: 0
      empathy: 3
      authority: 2
      suggestion: 3
      composure: 1
      agility: 0
      endurance: 1
    starting_equipment_ids:
      - "professional_attire"
      - "confidence_charm"
      - "voice_recorder"

  field:
    id: "field"
    name: "Field Detective"
    description: "You excel in the field, able to chase down suspects, maintain composure in dangerous situations, and tough out long hours. Your instincts are sharp, though you might miss subtle details or social cues."
    starting_skills:
      logic: 1
      perception: 2
      memory: 0
      empathy: 0
      authority: 1
      suggestion: 1
      composure: 3
      agility: 2
      endurance: 2
    starting_equipment_ids:
      - "sturdy_boots"
      - "weatherproof_jacket"
      - "first_aid_kit" 