---
# Main Game Configuration
# This file references the individual component files

include:
  - game_settings.yaml
  - character_archetypes.yaml
  - item_sets.yaml
  - items.yaml
  - locations.yaml
  - npcs.yaml
  - dialogue_trees.yaml
  - quests.yaml
  - inner_voices.yaml
  - thoughts.yaml 