---
# Quests Configuration

quests:
  main_investigation:
    id: "main_investigation"
    title: "The Warehouse Investigation"
    description: "Investigate the strange occurrences at the warehouse."
    short_description: "Investigate warehouse incidents"
    importance: "Critical"
    is_main_quest: true
    is_hidden: false
    status: "NotStarted"
    stages:
      - id: "initial_investigation"
        title: "Initial Investigation"
        description: "Gather information about the warehouse incident."
        status: "NotStarted"
        objectives:
          - id: "talk_to_guard"
            description: "Talk to Officer Martinez about the incident"
            is_completed: false
            is_optional: false
            completion_events:
              - event_type: "AddClue"
                data:
                  id: "guard_statement"
                  description: "The guard mentioned unusual activity in the warehouse"
                  related_quest: "main_investigation"
                  discovered: true
          - id: "inspect_door"
            description: "Examine the warehouse entrance for signs of forced entry"
            is_completed: false
            is_optional: false
            completion_events:
              - event_type: "AddClue"
                data:
                  id: "forced_entry"
                  description: "The door shows signs of forced entry"
                  related_quest: "main_investigation"
                  discovered: true
        notification_text: "You've started investigating the warehouse incident."
      - id: "search_office"
        title: "Search the Office"
        description: "Look for clues in the security office."
        status: "NotStarted"
        objectives:
          - id: "check_logbook"
            description: "Review the security log book"
            is_completed: false
            is_optional: false
            completion_events:
              - event_type: "AddClue"
                data:
                  id: "logbook_entry"
                  description: "The last entry in the logbook is incomplete"
                  related_quest: "main_investigation"
                  discovered: true
          - id: "talk_to_worker"
            description: "Interview Sarah Chen about the incident"
            is_completed: false
            is_optional: false
            completion_events:
              - event_type: "AddClue"
                data:
                  id: "worker_statement"
                  description: "Sarah mentioned seeing suspicious figures"
                  related_quest: "main_investigation"
                  discovered: true
        notification_text: "You've found new leads in the security office."
      - id: "conclusion"
        title: "Draw Conclusions"
        description: "Piece together the evidence and solve the case."
        status: "NotStarted"
        objectives:
          - id: "solve_case"
            description: "Present your findings to Officer Martinez"
            is_completed: false
            is_optional: false
            completion_events:
              - event_type: "CompleteQuest"
                data:
                  quest_id: "main_investigation"
                  reward: "case_solved"
        notification_text: "You've solved the warehouse case!"

missing_locket:
  id: "missing_locket"
  title: "The Missing Locket"
  description: "Help Eliza find her missing silver locket."
  short_description: "Find Eliza's lost locket"
  importance: "Optional"
  is_main_quest: false
  is_hidden: false
  status: "NotStarted"
  stages:
    - id: "search_town"
      title: "Search the Town"
      description: "Look for clues about the missing locket."
      status: "NotStarted"
      objectives:
        - id: "talk_to_eliza"
          description: "Get more information from Eliza about the locket"
          is_completed: false
          is_optional: false
          completion_events:
            - event_type: "AddClue"
              data:
                id: "locket_description"
                description: "A silver locket with a family portrait inside"
                related_quest: "missing_locket"
                discovered: true
        - id: "search_fountain"
          description: "Search around the town square fountain"
          is_completed: false
          is_optional: false
          completion_events:
            - event_type: "AddClue"
              data:
                id: "fountain_clue"
                description: "Found a thread that might be from the locket's chain"
                related_quest: "missing_locket"
                discovered: true
      notification_text: "You've started searching for the missing locket."
    - id: "find_locket"
      title: "Find the Locket"
      description: "Follow the clues to find the missing locket."
      status: "NotStarted"
      objectives:
        - id: "search_garden"
          description: "Search the garden for the locket"
          is_completed: false
          is_optional: false
          completion_events:
            - event_type: "AddItem"
              data:
                id: "silver_locket"
                name: "Silver Locket"
                description: "A beautiful silver locket with intricate engravings"
                effects: {}
            - event_type: "CompleteObjective"
              data:
                quest_id: "missing_locket"
                objective_id: "search_garden"
        - id: "return_locket"
          description: "Return the locket to Eliza"
          is_completed: false
          is_optional: false
          completion_events:
            - event_type: "CompleteQuest"
              data:
                quest_id: "missing_locket"
                reward: "eliza_gratitude"
      notification_text: "You've found the missing locket!"

chen_shift_help:
  id: "chen_shift_help"
  title: "Help Sarah Chen"
  description: "Sarah Chen seems stressed about her shift. Maybe you can help her out."
  short_description: "Help Sarah with her shift"
  importance: "Optional"
  is_main_quest: false
  is_hidden: false
  status: "NotStarted"
  related_npcs: ["worker_chen"]
  stages:
    - id: "talk_to_chen"
      title: "Talk to Sarah"
      description: "Find out what's bothering Sarah about her shift."
      status: "NotStarted"
      objectives:
        - id: "ask_about_shift"
          description: "Talk to Sarah about her shift"
          is_completed: false
          is_optional: false
          completion_events:
            - event_type: "AddClue"
              data:
                id: "chen_shift_problem"
                description: "Sarah is worried about completing her shift on time"
                related_quest: "chen_shift_help"
                discovered: true
      notification_text: "You've learned about Sarah's shift problems."
    - id: "help_chen"
      title: "Help Sarah"
      description: "Assist Sarah with her shift tasks."
      status: "NotStarted"
      objectives:
        - id: "complete_tasks"
          description: "Help Sarah complete her shift tasks"
          is_completed: false
          is_optional: false
          completion_events:
            - event_type: "CompleteQuest"
              data:
                quest_id: "chen_shift_help"
                reward: "chen_gratitude"
      notification_text: "You've helped Sarah complete her shift!"
  rewards:
    relationship_changes:
      worker_chen: 10
    experience: 50 